In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import sqlite3

Task 01: Data Import

In [2]:
conn = sqlite3.connect("../data/customer_churn.db")

print("Connected to SQLite database successfully!")

Connected to SQLite database successfully!

In [3]:

query = """
SELECT name
FROM sqlite_master
WHERE type = 'table';
"""

tables = pd.read_sql_query(query, conn)
print(tables)

              name
0      db_customer
1  db_subscription
2       db_support

In [12]:
df_customer = pd.read_sql_query("SELECT * FROM db_customer", conn)
df_subscription = pd.read_sql_query("SELECT * FROM db_subscription", conn)
df_support = pd.read_sql_query("SELECT * FROM db_support", conn)
conn.close()

Task 02: Data Cleaning 

In this task, we will clean the customer, subscription, and support datasets to improve data quality and prepare them for exploratory data analysis (EDA).

The following steps will be performed:

1. Rename column: name to customer_column
2. Drop unnecessary columns: interests and pincode
3. Handle missing values: country column
4. Correct data types: dob
5. Standardize inconsistent values: gender column

In [26]:
df_customer.tail()

,customerid,customer_id,country,state,gender,dob,interests,pincode
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,NaN,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,NaN,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,NaN,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,NaN,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,NaN,None

In [31]:
df_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customerid   21 non-null     str
 1   customer_id  21 non-null     str
 2   country      18 non-null     str
 3   state        21 non-null     str
 4   gender       21 non-null     str
 5   dob          21 non-null     datetime64[us]
 6   interests    4 non-null      str
 7   pincode      0 non-null      object
dtypes: datetime64[us](1), object(1), str(6)
memory usage: 1.4+ KB

1. Rename column: name to customer_column

In [25]:
df_customer.rename(columns={'name':'customer_id'}, inplace=True)

2. Drop unnecessary columns: interests and pincode

In [27]:
df_customer.drop(columns=['interests', 'pincode'])

    customerid customer_id country          state  gender                  dob
0   0002-ORFBO      keshav   India    Maharashtra    Male  1982-04-12 00:00:00
1   0003-MKNFE      raghav   India      Karnataka    Male  1995-11-23 00:00:00
2   0004-TLHLJ      lalita   India          Delhi  Female  1978-02-15 00:00:00
3   0011-IGKFF       mohan   India       Nagaland    Male  2001-08-30 00:00:00
4   0013-EXCHZ        mira   India          Delhi  Female  1990-05-05 00:00:00
5   0013-MHZWF       durga     NaN          Delhi   Women  1988-12-10 00:00:00
6   0013-SMEOE        mina   India      Meghalaya  Female  1976-09-21 00:00:00
7   0014-BMAQU       madan   India      Rajasthan    Male  1999-03-14 00:00:00
8   0015-UOCOJ        maya     NaN      Kathmandu   Women  1985-07-07 00:00:00
9   0016-QLJIS       arjun   Nepal      Kathmandu    Male  1993-10-29 00:00:00
10  0017-DINOC       shiva   India    Maharashtra     Men  1997-01-22 00:00:00
11  0017-IUDMW   rangadevi   India      Karnataka  Female  1981-06-18 00:00:00
12  0018-NYROU      chitra     NaN      Telangana  Female  2004-12-01 00:00:00
13  0019-EFAEP        raju   India      Meghalaya  Female  1992-04-25 00:00:00
14  0019-GFNTW      Madhav   India  Uttar Pradesh     Men  1979-11-11 00:00:00
15  0020-INWCK     parvati   India          Delhi  Female  1986-02-28 00:00:00
16  0020-JDNXP       rikim   India      Meghalaya  Female  1994-08-19 00:00:00
17  0021-IKXGC    vishakha   India      Rajasthan  Female  2000-09-02 00:00:00
18  0022-TCJCI  raghvendra   India      Telangana    Male  1983-12-30 00:00:00
19  0023-HGHWL     rishabh   India  Uttar Pradesh     Men  1991-05-14 00:00:00
20  0023-UYUPN      sudevi   India    Maharashtra   Women  1977-10-06 00:00:00

4. Correct data types: dob

In [30]:
df_customer['dob'] = pd.to_datetime(df_customer['dob'])

5. Standardize inconsistent values: gender column